openapi: 3.0.1
info:
  title: MyEcommerce.Services.ProductService.API
  version: v1
paths:
  "/api/Catalogs/{catalogId}/categories":
    get:
      tags:
        - Catalogs
      operationId: GetCategories
      parameters:
        - name: catalogId
          in: path
          required: true
          schema:
            type: string
            nullable: true
      responses:
        "200":
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CategoryReadDto"
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CategoryReadDto"
            text/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CategoryReadDto"
  /api/Products:
    get:
      tags:
        - Products
      operationId: GetAll
      parameters:
        - name: PageIndex
          in: query
          schema:
            type: integer
            format: int32
        - name: PageLimit
          in: query
          schema:
            type: integer
            format: int32
        - name: PageSort
          in: query
          schema:
            $ref: "#/components/schemas/ProductPageSortDto"
        - name: FilterIsNew
          in: query
          schema:
            type: boolean
        - name: FilterOnSale
          in: query
          schema:
            type: boolean
        - name: FilterMinPrice
          in: query
          schema:
            type: number
            format: double
            nullable: true
        - name: FilterMaxPrice
          in: query
          schema:
            type: number
            format: double
            nullable: true
        - name: FilterCategory.Id
          in: query
          schema:
            type: string
            nullable: true
        - name: FilterCategory.Name
          in: query
          schema:
            type: string
            nullable: true
        - name: FilterTags
          in: query
          schema:
            type: array
            items:
              type: string
            nullable: true
      responses:
        "200":
          description: Success
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/PaginatedProductsDto"
            application/json:
              schema:
                $ref: "#/components/schemas/PaginatedProductsDto"
            text/json:
              schema:
                $ref: "#/components/schemas/PaginatedProductsDto"
    post:
      tags:
        - Products
      operationId: CreateAsync
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductCreateDto"
          text/json:
            schema:
              $ref: "#/components/schemas/ProductCreateDto"
          application/*+json:
            schema:
              $ref: "#/components/schemas/ProductCreateDto"
      responses:
        "200":
          description: Success
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/ProductReadDto"
            application/json:
              schema:
                $ref: "#/components/schemas/ProductReadDto"
            text/json:
              schema:
                $ref: "#/components/schemas/ProductReadDto"
        "400":
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
            text/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
  "/api/Products/{id}":
    get:
      tags:
        - Products
      operationId: GetById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            nullable: true
      responses:
        "200":
          description: Success
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/ProductReadDto"
            application/json:
              schema:
                $ref: "#/components/schemas/ProductReadDto"
            text/json:
              schema:
                $ref: "#/components/schemas/ProductReadDto"
        "404":
          description: Not Found
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
            text/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
components:
  schemas:
    CategoryReadDto:
      type: object
      properties:
        id:
          type: string
          nullable: true
        name:
          type: string
          nullable: true
      additionalProperties: false
    ProductPageSortDto:
      enum:
        - 0
        - 1
        - 2
        - 3
      type: integer
      format: int32
    TagReadDto:
      type: object
      properties:
        id:
          type: string
          nullable: true
        group:
          type: string
          nullable: true
        name:
          type: string
          nullable: true
      additionalProperties: false
    ProductReadDto:
      type: object
      properties:
        id:
          type: string
          nullable: true
        name:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
        price:
          type: number
          format: double
        salePrice:
          type: number
          format: double
          nullable: true
        imageFileName:
          type: string
          nullable: true
        imageUri:
          type: string
          nullable: true
        availableStock:
          type: integer
          format: int32
        restockTreshold:
          type: integer
          format: int32
        maxStockThreshold:
          type: integer
          format: int32
        onReorder:
          type: boolean
        isNew:
          type: boolean
        onSale:
          type: boolean
        categories:
          type: array
          items:
            $ref: "#/components/schemas/CategoryReadDto"
          nullable: true
        tags:
          type: array
          items:
            $ref: "#/components/schemas/TagReadDto"
          nullable: true
      additionalProperties: false
    TagSummaryDto:
      type: object
      properties:
        numProducts:
          type: integer
          format: int32
        tag:
          $ref: "#/components/schemas/TagReadDto"
      additionalProperties: false
    TagGroupSummaryDto:
      type: object
      properties:
        group:
          type: string
          nullable: true
        tagSummaries:
          type: array
          items:
            $ref: "#/components/schemas/TagSummaryDto"
          nullable: true
      additionalProperties: false
    PaginatedProductsDto:
      type: object
      properties:
        hasMore:
          type: boolean
        pageIndex:
          type: integer
          format: int32
        pageLimit:
          type: integer
          format: int32
        totalProducts:
          type: integer
          format: int32
        products:
          type: array
          items:
            $ref: "#/components/schemas/ProductReadDto"
          nullable: true
        tagGroupSummaries:
          type: array
          items:
            $ref: "#/components/schemas/TagGroupSummaryDto"
          nullable: true
      additionalProperties: false
    ProductCreateDto:
      required:
        - description
        - name
        - price
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        price:
          type: number
          format: double
        salePrice:
          type: number
          format: double
          nullable: true
        imageFileName:
          type: string
          nullable: true
        imageUri:
          type: string
          nullable: true
        availableStock:
          type: integer
          format: int32
        restockTreshold:
          type: integer
          format: int32
        maxStockThreshold:
          type: integer
          format: int32
        onReorder:
          type: boolean
        isNew:
          type: boolean
        categories:
          type: array
          items:
            $ref: "#/components/schemas/CategoryReadDto"
          nullable: true
        tags:
          type: array
          items:
            $ref: "#/components/schemas/TagReadDto"
          nullable: true
      additionalProperties: false
    ProblemDetails:
      type: object
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
      additionalProperties: {}
